gt9147
RT-Thread-packages/gt9147 pull request #1
Opened 2019-06-04 09:32 UTC by tyustli

add gt9147 packages

2019-06-11 22:19 UTC, BernardXiong commented
请在两类以上开发板上验证通过，同时请再review其中的代码实现，需要保持代码风格与RT-Thread的一致

2019-06-15 01:49 UTC, yqiu2018 requested changes

2019-06-15 01:49 UTC, yqiu2018 commented on samples/gt9147_sample.c
> +static int gt9147_sample(void)
touch 名称，x， y 可以作为参数传入

2019-06-15 02:41 UTC, yqiu2018 commented on samples/gt9147_sample.c
> +        rt_kprintf("can't find device:%s\n", "gt");
rt_kprintf("can't find device:%s\n", "gt");

2019-06-15 03:23 UTC, merged